# Configuración de la Base de Datos - Aiven MySQL (Gratis)
spring.datasource.url=jdbc:mysql://wembley-db-01-emimonson8-bdba.i.aivencloud.com:21670/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# 'update' creará las tablas automáticamente en la nube si no existen
# Cambiá 'create' por 'update' para no borrar tus productos cada vez que reinicies
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.sql.init.mode=always


spring.jpa.properties.hibernate.format_sql=true

# 3. Asegurate de que el dialecto sea este exacto



# Configuración del Servidor
server.port=8080