# Paso 1: Usar una imagen de Maven para compilar el proyecto
FROM maven:3.8.4-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

# Paso 2: Usar una imagen liviana de Java para correr la app
FROM openjdk:17-jdk-slim
COPY --from=build /target/utileria-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]